def myOpen(): 
  HOSTNAME = "192.168.1.63"
  PORT = 5000
  pi = 3.14159265359
  socket_open(HOSTNAME, PORT)
  socket_send_string("Iniciando")
  global grip_detected = False
  global lost_grip = False
  if(True == get_digital_in(8)):
    grip_detected = True
  end
  set_analog_inputrange(2, 1)
  sync()
  sync()
  sync()
  global measure_width = (floor(((get_analog_in(2)-0.026)*110/2.976)*10))/10
end